// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrPxodcilC-MJXM4Okz6WXwv6ejPW8IXM',
    appId: '1:92008976043:web:4ca6db80df449cf38af1ee',
    messagingSenderId: '92008976043',
    projectId: 'magistro-e1535',
    authDomain: 'magistro-e1535.firebaseapp.com',
    storageBucket: 'magistro-e1535.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuD_S_b984tpVu7yBrsJvYX5q0Vhybg5A',
    appId: '1:92008976043:android:c949c8ff5f22cb7e8af1ee',
    messagingSenderId: '92008976043',
    projectId: 'magistro-e1535',
    storageBucket: 'magistro-e1535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8YSCBGe8DvWk0INFkSZAvs9eV98p0RC4',
    appId: '1:92008976043:ios:4d0ef5e6c0174a8e8af1ee',
    messagingSenderId: '92008976043',
    projectId: 'magistro-e1535',
    storageBucket: 'magistro-e1535.appspot.com',
    iosClientId: '92008976043-5ue4ts9l718jmln3i0jsr3re10c6tgtv.apps.googleusercontent.com',
    iosBundleId: 'com.example.magistro',
  );
}
